name: push触发服务器部署

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute script on server
        run: |
          ssh -o StrictHostKeyChecking=no root@47.121.117.97 << EOF
            cd /www/wwwroot
            if [ -d "home-site" ]; then
                git pull origin main
            else
                git clone https://github.com/xxxsjan/home-site
            fi
            cd /www/wwwroot/home-site
            git pull origin main
            git checkout main
            npm install
            npm run build
            pm2 delete home-site | true
            pm2 start npm --name "home-site" -- run start
            pm2 save
          EOF