name: push触发服务器部署

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute script on server
        run: |
          REMOTE_SERVER="root@47.121.117.97"
          ROOT_DIR="/www/wwwroot"
          PROJECT_NAME="home-site"
          PROJECT_DIR="$ROOT_DIR/$PROJECT_NAME"
          GITHUB_USER="xxxsjan"
          REPO_URL="https://github.com/${GITHUB_USER}/${PROJECT_NAME}"

          SSH_COMMAND="ssh -o StrictHostKeyChecking=no $REMOTE_SERVER << EOF
              cd $ROOT_DIR
              if [ -d \"$PROJECT_NAME\" ]; then
                  git -C $PROJECT_DIR pull origin main
              else
                  git clone $REPO_URL
              fi
              cd $PROJECT_DIR
              git pull origin main
              git checkout main
              npm install
              npm run build
              pm2 delete $PROJECT_NAME || true
              pm2 start npm --name \"$PROJECT_NAME\" -- run start
              pm2 save
          EOF"

          eval "$SSH_COMMAND"